### ISSUE TITLE
[Enhancement] [zos_backup_restore] Support - SHPERE

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1539]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enhancement or feature description

This is part of Epic #1180 and collaboration #1530.
Consider reviewing JCL [examples](https://www.ibm.com/docs/en/zos/2.2.0?topic=dfsmsdss-examples-physical-data-set-restore-operations). 

| Keyword               | Status  | 
| --------------------- | ------- | 
| [SHPERE](https://github.com/ansible-collections/ibm_zos_core/issues/1180#shpere) | accepted | 

Proposal:
Examples:

### Ansible module

zos_backup_restore

**Comment by fernandofloresg** [comment]
JCL to create an AIX (alternate index) 

```jcl
echo "  DEFINE ALTERNATEINDEX (NAME(OMVSADM.TEST.AIX) -
  RELATE(OMVSADM.TEST.KSDS) -
  KEYS(5 0) -
  VOLUMES(000000) -
  TRACKS(1 1) -
  FREESPACE(10 10) -
  NONUNIQUEKEY) -
  DATA (NAME(OMVSADM.TEST.AIX.DATA)) -
  INDEX (NAME(OMVSADM.TEST.AIX.INDEX))  " | mvscmdauth --pgm=IDCAMS --sysprint=* --sysin=stdin

```

**Comment by fernandofloresg** [comment]
Tried this and looks like is failing with ZOAU 1.3.6 and 1.4.0, we do not need this to get fixed in 1.3.6 only 1.4.0:

```bash


Using ZOAU version 1.4.0
Using python version 3.13
Bash is enabled.
[ OMVSADM:/u/omvsadm: ]dtouch -tksds -k4:0 omvsadm.test.ksds
< "  DEFINE ALTERNATEINDEX (NAME(OMVSADM.TEST.AIX) -                         
>   RELATE(OMVSADM.TEST.KSDS) -
>   KEYS(5 0) -
>   VOLUMES(000000) -
>   TRACKS(1 1) -
>   FREESPACE(10 10) -
>   NONUNIQUEKEY) -
>   DATA (NAME(OMVSADM.TEST.AIX.DATA)) -
<T.AIX.INDEX))  " | mvscmdauth --pgm=IDCAMS --sysprint=* --sysin=stdin       

1IDCAMS  SYSTEM SERVICES                                           TIME: 20:36:44        09/03/25     PAGE      1
0        
   DEFINE ALTERNATEINDEX (NAME(OMVSADM.TEST.AIX) -
   RELATE(OMVSADM.TEST.KSDS) -
   KEYS(5 0) -
   VOLUMES(000000) -
   TRACKS(1 1) -
   FREESPACE(10 10) -
   NONUNIQUEKEY) -
   DATA (NAME(OMVSADM.TEST.AIX.DATA)) -
   INDEX (NAME(OMVSADM.TEST.AIX.INDEX))
0IDC0508I DATA ALLOCATION STATUS FOR VOLUME 000000 IS 0
0IDC0509I INDEX ALLOCATION STATUS FOR VOLUME 000000 IS 0
0IDC0001I FUNCTION COMPLETED, HIGHEST CONDITION CODE WAS 0
0        
0IDC0002I IDCAMS PROCESSING COMPLETE. MAXIMUM CONDITION CODE WAS 0
[ OMVSADM:/u/omvsadm: ]
[ OMVSADM:/u/omvsadm: ]python3
Python 3.13.0 (heads/pyz_dev-3.13:bd1cf5a763, Oct 31 2024, 14:42:31) [Clang 18.1.0 (build 221a599)] on zos
Type "help", "copyright", "credits" or "license" for more information.
>>> from zoautil_py import datasets
>>> keywords = {"sphere": True}
>>> rc = datasets.dzip('omvsadm.test.backup', 'omvsadm.test.ksds', dataset=True\
                                                                                Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    rc = datasets.dzip('omvsadm.test.backup', 'omvsadm.test.ksds', dataset=True, keywords=keywords)
  File "/zoau/v1.4.0/lib/3.13/zoautil_py/datasets.py", line 2420, in dzip
    raise ZOAUException(response)
zoautil_py.exceptions.ZOAUException: [ZOAUResponse]
	rc: 8
	response_format: UTF-8
	stdout_response: 
	stderr_response: BGYSC3904E Failed to dump contents for zip file, see RC for mvscmd return code.
1PAGE 0001     5695-DF175  DFSMSDSS V2R05.0 DATA SET SERVICES     2025.246 20:38
- DUMP OUTDD(ARCHIVE) OPTIMIZE(4) -
  DS(INCL( -
  OMVSADM.TEST.KSDS, -
  ) -
  ) -
  SPHERE(TRUE) -
  
 ADR101I (R/I)-RI01 (01), TASKID 001 HAS BEEN ASSIGNED TO COMMAND 'DUMP '
 ADR109I (R/I)-RI01 (01), 2025.246 20:38:15 INITIAL SCAN OF USER CONTROL STATEMENTS COMPLETED
 ADR124E (001)-RI01 (02), DELIMITER '(' IS NOT PROPERLY PRECEDED BY A CONSTANT OR KEYWORD
 ADR131E (001)-RI03 (01), ABOVE TEXT BYPASSED UNTIL NEXT COMMAND
 ADR017E (001)-CLTSK(01), 2025.246 20:38:15 TASK NOT SCHEDULED DUE TO ERROR. TASK RETURN CODE 0008
0ADR012I (SCH)-DSSU (01), 2025.246 20:38:15 DFSMSDSS PROCESSING COMPLETE. HIGHEST RETURN CODE IS 0008 FROM:
                          SYNTAX
                          TASK    001

	command: dzip -D --keyword="sphere(True)" "omvsadm.test.backup" "omvsadm.test.ksds"
```
