### ISSUE TITLE
[Enhancement] [zos_job_query]  to allow leading wildcard for job_name parm

### ISSUE THREAD

**Issue by adn1107** [ansible-collections/ibm_zos_core#662]
### Enhancement or featture description

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_zos_job_query_payload_plhn0cl3/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py", line 165, in run_module
  File "/tmp/ansible_zos_job_query_payload_plhn0cl3/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py", line 189, in validate_arguments
RuntimeError: Failed to validate the job name: *HWS

### Ansible module

zos_job_query

**Comment by ddimatos** [comment]
@adn1107 - this appears to be a duplicate to issue #323 , thus I will close this. 
@richp405 please verify your current #323 work covers this closing issue.
