### ISSUE TITLE
[Bug] [zos_job_query] a short job name less than 8 that includes a wildcard such as  “STC000*” throws index error

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#900]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.4

### IBM Enterprise Python

v3.9.x

### IBM z/OS Ansible core Version

v1.7.0-beta.1

### ansible-version

v2.15.x

### z/OS version

v2.5

### Ansible module

zos_job_query

### Bug description

This issue appears to be in ZOAU which for the ansible team its simply validation once a fix is available. 

The use case case is to drive a `zos_job_query` with a regular expression that will cause about 40+ jobs to return such as ` “STC000*”`

`TypeError: Value of unknown type: <class 'IndexError'>, list index out of range`

The playbook can be:
```
---
- hosts: zvm
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  vars:
    stc_id_valid_regex: "STC000*"

  environment: "{{ environment_vars }}"

  tasks:
    - name: Get zos_job_query
      zos_job_query:
        job_id: "{{ stc_id_valid_regex }}"
      register: result

    - name: Result
      debug:
        msg: "{{ result }}"
```

Will produce:
```
Traceback (most recent call last):
  File \"/tmp/ansible_zos_job_query_payload_9ngjs4xc/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 282, in run_module
  File \"/tmp/ansible_zos_job_query_payload_9ngjs4xc/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 356, in query_jobs
  File \"/tmp/ansible_zos_job_query_payload_9ngjs4xc/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/job.py\", line 164, in job_status
  File \"/tmp/ansible_zos_job_query_payload_9ngjs4xc/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/job.py\", line 278, in _get_job_status
  File \"/zoau/latest/lib/zoautil_py/jobs.py\", line 283, in list_dds
    \"dataset\": dataset_definition[2],
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"/tmp/ansible-tmp-1689661438.870805-42824-211569005103724/AnsiballZ_zos_job_query.py\", line 107, in <module>
    _ansiballz_main()
  File \"/tmp/ansible-tmp-1689661438.870805-42824-211569005103724/AnsiballZ_zos_job_query.py\", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/tmp/ansible-tmp-1689661438.870805-42824-211569005103724/AnsiballZ_zos_job_query.py\", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ibm.ibm_zos_core.plugins.modules.zos_job_query', init_globals=dict(_module_fqn='ansible_collections.ibm.ibm_zos_core.plugins.modules.zos_job_query', _modlib_path=modlib_path),
  File \"/allpython/3.9/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/runpy.py\", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File \"/allpython/3.9/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/runpy.py\", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File \"/allpython/3.9/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/runpy.py\", line 87, in _run_code
    exec(code, run_globals)
  File \"/tmp/ansible_zos_job_query_payload_9ngjs4xc/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 431, in <module>
  File \"/tmp/ansible_zos_job_query_payload_9ngjs4xc/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 427, in main
  File \"/tmp/ansible_zos_job_query_payload_9ngjs4xc/ansible_zos_job_query_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_query.py\", line 289, in run_module
  File \"/tmp/ansible_zos_job_query_payload_9ngjs4xc/ansible_zos_job_query_payload.zip/ansible/module_utils/basic.py\", line 1541, in fail_json
  File \"/tmp/ansible_zos_job_query_payload_9ngjs4xc/ansible_zos_job_query_payload.zip/ansible/module_utils/basic.py\", line 1514, in _return_formatted
  File \"/tmp/ansible_zos_job_query_payload_9ngjs4xc/ansible_zos_job_query_payload.zip/ansible/module_utils/common/parameters.py\", line 927, in remove_values
  File \"/tmp/ansible_zos_job_query_payload_9ngjs4xc/ansible_zos_job_query_payload.zip/ansible/module_utils/common/parameters.py\", line 470, in _remove_values_conditions
TypeError: Value of unknown type: <class 'IndexError'>, list index out of range
",
```

And this can be an isolated recreate by doing:
```
>>> from zoautil_py.types import ZOAUResponse
>>> from zoautil_py import jobs, datasets

>>> entries=jobs.listing("STC000*")
>>> for entry in entries:
...   list_of_dds = jobs.list_dds(entry.id)
...   print(list_of_dds)
...
```

Which returns:
```
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '15', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '7', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '12', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '28', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}, {'stepname': 'IZUANG1', 'dataset': 'STDOUT', 'format': 'VB', 'length': '16383', 'recnum': '0', 'dsid': '101'}, {'stepname': 'IZUANG1', 'dataset': 'STDERR', 'format': 'VB', 'length': '16383', 'recnum': '0', 'dsid': '102'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '92', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}, {'stepname': 'IZUSVR1', 'dataset': 'STDERR', 'format': 'VB', 'length': '16383', 'recnum': '1', 'dsid': '106'}, {'stepname': 'IZUSVR1', 'dataset': 'STDOUT', 'format': 'VB', 'length': '16383', 'recnum': '16', 'dsid': '107'}, {'stepname': 'IZUSVR1', 'dataset': 'STDOUT', 'format': 'VB', 'length': '16383', 'recnum': '17215', 'dsid': '108'}, {'stepname': 'IZUSVR1', 'dataset': 'STDERR', 'format': 'VB', 'length': '16383', 'recnum': '0', 'dsid': '109'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '30', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '299', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '37', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '15', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '33', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '37', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '61', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}, {'stepname': 'RMF', 'dataset': 'RMFSCZZ', 'format': 'VBA', 'length': '125', 'recnum': '0', 'dsid': '102'}, {'stepname': 'RMF', 'dataset': 'MFMESSGE', 'format': 'VBA', 'length': '125', 'recnum': '0', 'dsid': '101'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '68', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '2', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '37', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '2', 'dsid': '4'}, {'stepname': 'SDSF', 'dataset': 'HSFTRACE', 'format': 'VB', 'length': '256', 'recnum': '0', 'dsid': '102'}, {'stepname': 'SDSF', 'dataset': 'HSFLOG', 'format': 'VB', 'length': '256', 'recnum': '0', 'dsid': '101'}]
[{'stepname': 'JES2', 'dataset': 'JESMSGLG', 'format': 'UA', 'length': '133', 'recnum': '13', 'dsid': '2'}, {'stepname': 'JES2', 'dataset': 'JESJCL', 'format': 'V', 'length': '136', 'recnum': '15', 'dsid': '3'}, {'stepname': 'JES2', 'dataset': 'JESYSMSG', 'format': 'VA', 'length': '137', 'recnum': '24', 'dsid': '4'}, {'stepname': 'IRRDPTAB', 'dataset': 'SYSTSPRT', 'format': 'VBA', 'length': '137', 'recnum': '2', 'dsid': '101'}]
[{'stepname': 'JES2', 'dataset': 'SYSLOG00', 'format': 'U', 'length': '130', 'recnum': '9444', 'dsid': '101'}]
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/zoau/latest/lib/zoautil_py/jobs.py", line 283, in list_dds
    "dataset": dataset_definition[2],
IndexError: list index out of range
>>>

### Playbook verbosity output.

_No response_

### Ansible configuration.

_No response_

### Contents of the inventory

_No response_

### Contents of `group_vars` or `host_vars`

_No response_

**Comment by ddimatos** [comment]
This relates to zoau tracker: NAZARE-10018
